driver: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://mysql26.mysql.database.azure.com:3306/snowman?useSSL=true&requireSSL=true
username: surajjp74
password: Mysql123@
verbose: true
dropFirst: false
changeLogFile: src/main/resources/db/liquibase-changelog-schema.xml
