driver: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://mysql26.mysql.database.azure.com:3306/$(dbname)?useSSL=true&requireSSL=true
username: $(dbuser)
password: $(dbpassword)
verbose: true
dropFirst: false
changeLogFile: src/main/resources/db/liquibase-changelog-schema.xml