# jdbc.X
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://mysql26.mysql.database.azure.com:3306/snowman?useSSL=true&requireSSL=true
jdbc.username=surajjp74
jdbc.password=Mysql123@

# hibernate.X
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.show_sql=true
# validate | update | create | create-drop
hibernate.hbm2ddl.auto=update

# Messaging - JMS
jms.brokerUrl=tcp://localhost:61616
