trigger: none

pool:
  name: vm-agent

stages:
  - stage: Deploy
    displayName: Deploy & Run Liquibase

    jobs:
      - job: DeployJob
        displayName: Deployment Job

        steps:
          # Download artifact from CI
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'jar'
              downloadPath: '$(System.ArtifactsDirectory)'

          # Run Liquibase
          - script: |
              echo "Running Database"

              mvn liquibase:update \
                -Dliquibase.url=jdbc:mysql://mysql26.mysql.database.azure.com:3306/snowman?useSSL=true\&requireSSL=true \
                -Dliquibase.username=${db-username} \
                -Dliquibase.password=${db-password}

            displayName: Run Database

          # Confirmation step (separate step)
          - script: |
              echo "Database Injected successfully"
            displayName: DB Success Message

          # Run your application (optional)
          # - script: |
            #  echo "Starting Application..."
             # java -jar $(System.ArtifactsDirectory)/jar/*.jar
            # displayName: Run Application