trigger: none

variables:
- group: Kv-secrets

pool:
  name: vm-agent

stages:
# Stage 1: BUILD
- stage: Build
  displayName: Build

  jobs:
  - job: MavenBuild
    displayName: Maven Build Job

    steps:    #Build with Java 8
    - script: |
        echo "Using Java 8 for Build"
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
        mvn clean package \
          -DskipTests \
          -Dliquibase.skip=true
      displayName: Build with Java 8

    #Publish target folder
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'target'
        artifactName: 'build-output'
      displayName: Publish Build Artifacts

# Stage 2: SonarQube

- stage: SonarQube
  displayName: SonarQube Analysis
  dependsOn: Build  

  jobs:
  - job: SonarAnalysis
    displayName: SonarAnalysis Job

    steps:
    #Download artifacts
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'build-output'
        downloadPath: '$(System.DefaultWorkingDirectory)'
      displayName: Download Build Artifacts

    #SonarQube
    - script: |
        echo "Switching to Java 17 for Sonar"
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
        mvn sonar:sonar \
          -Dsonar.java.binaries=build-output/classes \
          -Dliquibase.skip=true \
          -Dsonar.projectKey=snowman-app \
          -Dsonar.host.url=http://20.197.61.229:9000/ \
          -Dsonar.login=$(sonarqube-token)
      displayName: SonarQube Analysis

# Stage 2: Dockerfile

